@echo off
set project=Chonki without Rhapsody boilerplate
set build_path=D:\HISE Projects\Chonki without Rhapsody boilerplate\DspNetworks\Binaries
set msbuild="C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\MsBuild.exe"
set vs_args=/p:Configuration="Release" /verbosity:minimal
set PreferredToolArchitecture=x64
set VisualStudioVersion=18.0

"C:\Users\Ibrahim Rasyid\Documents\HISE\JUCE\Projucer\Projucer.exe" --resave "%build_path%\AutogeneratedProject.jucer"

echo Compiling 64bit  %project% ...
set Platform=X64
%msbuild% "%build_path%\Builds\VisualStudio2026\%project%.sln" %vs_args%



